spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: webchat
    password: webchat
    driver-class-name: oracle.jdbc.driver.OracleDriver
    name: defaultDataSource
  mvc:
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    add-mappings: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 9090
  address: 127.0.0.1
  context-path: /
  session:
    timeout: 20

#使用log4j2替代默认的logback,1.在pom.xml的spring-boot-start中排除logback;2.在application.yml中配置log4j2.xml
logging:
  config: classpath:config/log4j2.xml
  level: info



